name: Run Script and Commit

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string
      python-version:
        required: true
        type: string

jobs:
  run-script:
    runs-on: ${{ inputs.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Pull files
        shell: pwsh
        run: |

          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git pull origin main

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python-version }}

      - name: Run script
        run: python create_pickle_data.py

      - name: Commit new page
        shell: pwsh
        run: |

          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add PickleDataFolder/
          git commit -m "Automated commit before push" || echo "No changes to commit"

          # Retry push up to 5 times
          $maxRetries = 5
          $retryCount = 0
          while ($retryCount -lt $maxRetries) {
          git push origin main
          if ($LASTEXITCODE -eq 0) {
          Write-Output "Push succeeded."
          break
          } else {
              Write-Output "Push failed, retrying after rebase..."
              git pull --rebase origin main
              $retryCount++
          }
          }

          if ($retryCount -eq $maxRetries) {
              Write-Output "Push failed after multiple attempts."
              exit 1
          }
