name: Cross-Platform Test

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: [3.8, 3.9, 3.11]
    steps:
      - name: Checkout code
        if: always()
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Run script
        if: always()
        run: python pickletest.py

      - name: Commit new page
        if: always()
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        
          git fetch origin main
          git checkout main
        
          $gitStatus = git status --porcelain
          Write-Output $gitStatus
        
          if ($gitStatus -ne "") {
            git add PickleDataFolder/
            git commit -m "Automated commit before rebase"
          }
        
          git pull --rebase origin main
        
          $maxRetries = 5
          $retryCount = 0
          $success = $false
        
          while (-not $success -and $retryCount -lt $maxRetries) {
            try {
              git push origin main
              $success = $true
            } catch {
              Write-Output "Push failed. Retrying in 5 seconds..."
              Start-Sleep -Seconds 5
              git pull --rebase origin main
              $retryCount++
            }
          }
        
          if (-not $success) {
            Write-Error "Push failed after $maxRetries attempts."
            exit 1
          }
        shell: pwsh
  
  deploy:
    needs: test
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to github pages
        id: deployment
        uses: actions/deploy-pages@v4

  check:
    needs: deploy
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Run Pickle1.py
        if: always()
        run: python Pickle1.py